Repository jergiemascan/grupparbete, pull requests merged in 2021-09, with the labels that each got.

#12 🤠 Menu page
  css/Main-css.css
  css/menu-css.css
  home-index.html
  menu.html
Labels: Success!

#14 header burger done
  css/Main-css.css
  home-index.html
Labels: documentation

#28 Final changes on gallery
  css/Main-css.css
  css/gallery-css.css
Labels: review needed
